baseurl = "https://joyofanalysis.com/"
title = "The Joy of Analysis"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "G"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "G"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Data Soup for the Soul"
    #description = ""
    #github = "https://github.com/XXX"
    #gitlab = "https://gitlab.com/XXX"
    #linkedin = "https://linkedin.com/in/XXX/"
    #gplus = "https://google.com/+XXX"
    #twitter = "https://twitter.com/XXX"
    #stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
    #facebook = "https://www.facebook.com/username"
    #email = "XXX@example.com"
    opengraph = false
    shareTwitter = false
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false
    readingTime = false
    readingTimeText = "Estimated reading time:"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
